### ISSUE TITLE
Official HomeAssistant integration

### ISSUE THREAD

**Issue by starkillerOG** [JimStar/reolink_ip#3]
Hi @JimStar,

I am planning to make a official Reolink HomeAssistant integration.
I have done that before and am code-owner of multiple integrations (Motion_blinds, Netgear, Xiaomi_miio).

I would like to base the official HomeAssistant inegration on your custom component (reolink_ccv) and this api library (reolink_ip).
Would you be intrested in helping me in this effort and maybe also becoming a code-owner of the official integration once that is made?
If so, could I possibly get acces to reolink_ccv and reolink_ip (make me a collabarotor) such that I can merge PRs, to speed up development?
(I could also fork, but I think it is nicer to not add to the confusion by making onother fork and I would like your help in maintenance if you would like to).

My plan is to first smooth out the current custom component:
 - make setup easier by reducing the amount of settings/options such as not having to supply the channels that you want to set up, but just setup all channels which have a camera connected, see https://github.com/JimStar/reolink_ip/pull/2.
 - Split the HomeAssistant device to a NVR device and a device per camera, add camera model info etc.
 - Only add sensors/switches which the camera supports (leverage the GetAbility)
 - Investigate if ONVIF protocol can be enabled through API (to prevent issues for users), supportOnvifEnable schould be investigated (see https://github.com/JimStar/reolink_ip/pull/4)

Once that is done, I want to first simplify the homeassistant custom component in a seperate branch/fork by stripping everything except for the camera entities to drastically reduce the amount of HomeAssistant code. (HomeAssistant only excepts a single platform for new integrations to reduce complexity and speed up code review).
Then make a PR for the new official component.
Once that is merged, make seperate PRs to add back all platforms, starting with the binary_sensors then switches etc.

Does this sound reasonable to you @JimStar?

**Comment by JimStar** [comment]
Thank you so much @starkillerOG for useful PRs.

Actually I started this fork mostly for the reason of being able to make my own decisions regrading all the details of *my view* of features' usefulness, code formatting, etc... I do it for enjoyment of a pet-project and code it exactly the way I like it for my own house's CCTV system. I don't like to have long arguing/discussions with anybody regarding "how this and that should be done" - I have enough of this at my main job. This one is just a "relaxing coding" for my free time... And I definitely have a lot of very different view in many aspects of "how things should be done". So for the *pet project* I like to just do it how I like it, not spending nerves and time on arguing with anybody... :)  
For example, I definitely don't like this:  
> Split the HomeAssistant device to a NVR device and a device per camera, add camera model info etc.

or this  
> stripping everything except for the camera entities

...breaking the whole code just to get a PR acceptance from somebody... Meh...

So I think it maybe a best way to go for you would be just fork it and do whatever you like with it as a base for your own projects... Most likely I would still continue using this unofficial HACS integration instead of HA-official one, if it had the above-mentioned "split devices" change...

**Comment by starkillerOG** [comment]
@JimStar Thank you for the greath work on this library and for the very quick replays!

I defently do get what you mean about long discussions.... pfff.... it can be really frustrating dealing with the core homeassistant team sometimes.
But in the end I do get why they do it, if they are not so strickt a project as big as HomeAssistant would get one big mess in no time.

Of course it needs to keep beeing fun :)

I will try to get as much done in PRs here, just because I really like your work and do not want to miss out on your efforts.
I think we can still share the reolink_ip library since that does not have to comply with the HomeAssistant standards ;)

I will at some point fork to try and get at least the basis supported in HomeAssistant as a official component.
We will see how things end up...
